require("plugins.packer")

require("plugins.catppuccin")
require("plugins.remap")
require("plugins.telescope")
require("plugins.barbar")
require("plugins.lualine")
require("plugins.nvimtree")
require("plugins.undotree")
require("plugins.toggleterm")
require("plugins.nvimcomment")
require("plugins.set")
require("plugins.gitsign")
require("plugins.treesitter")
require("plugins.undotree")
require("plugins.lsp-config")
